#!/bin/bash +O sourcepath

FLUXCAP_HOME=${PWD}
CONFIGFILE=$1
if [ -z "${CONFIGFILE}" ]; then
    echo "Usage: $0 <configFile>"
    exit 1
fi
. ${CONFIGFILE}

EMR_EC2_ATTRIBUTES="InstanceProfile=${EMR_EC2_ROLE}"
if [ -n "${EMR_EXTRA_EC2_ATTRIBUTES}" ]; then
    EMR_EC2_ATTRIBUTES="${EMR_EC2_ATTRIBUTES},${EMR_EXTRA_EC2_ATTRIBUTES}"
fi

EMR_BA_DRILL="Path=${FLUXCAP_S3_URL}/emr/exec/setup_drill,Name=setup_drill"
EMR_BA_DRILL_LIB_JETS3T="Path=${FLUXCAP_S3_URL}/emr/exec/setup_drill_lib_jets3t,Name=setup_drill_lib_jets3t"
EMR_BA_DRILL_LIB_AWS="Path=${FLUXCAP_S3_URL}/emr/exec/setup_drill_lib_aws,Name=setup_drill_lib_aws"
EMR_BA_HIVE_METASTORE="Path=${FLUXCAP_S3_URL}/emr/exec/start_hive_metastore,Name=start_hive_metastore"
EMR_BA_DRILL_STORAGE_STREAMS="Path=${FLUXCAP_S3_URL}/emr/exec/configure_drill_storage_streams,Name=configure_drill_storage_streams"
EMR_BA_DRILL_STORAGE_STREAM_ARCHIVES="Path=${FLUXCAP_S3_URL}/emr/exec/configure_drill_storage_stream_archives,Args=[${STREAM_ARCHIVES_DFS_URL},${STREAM_ARCHIVES_PATH}],Name=configure_drill_storage_stream_archives"
EMR_BOOTSTRAP_ACTIONS="${EMR_BA_DRILL} ${EMR_BA_DRILL_LIB_JETS3T} ${EMR_BA_DRILL_LIB_AWS} ${EMR_BA_HIVE_METASTORE} ${EMR_BA_DRILL_STORAGE_STREAMS} ${EMR_BA_DRILL_STORAGE_STREAM_ARCHIVES}"

EMR_CONFIG_STEPS="Name=hive_create_table_for_stream,Type=HIVE,Args=[-f,${FLUXCAP_S3_URL}/emr/hive/create_table_for_stream,-hiveconf,tablename=${STREAM_HIVE_TABLE_NAME},-hiveconf,streamname=${STREAM_NAME}]"

aws --profile "${AWS_PROFILE}" emr create-cluster \
 --ami-version ${EMR_AMI_VERSION} \
 --instance-groups ${EMR_INSTANCE_GROUPS} \
 --name "${EMR_CLUSTER_NAME}" \
 --service-role ${EMR_SERVICE_ROLE} \
 --ec2-attributes ${EMR_EC2_ATTRIBUTES} \
 --applications ${EMR_APPLICATIONS} \
 --bootstrap-actions ${EMR_BOOTSTRAP_ACTIONS} \
 --steps ${EMR_CONFIG_STEPS} \
 ${EMR_EXTRA_CLUSTER_OPTIONS}
