#!/bin/bash

# Copyright (C) 2015 Commerce Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Assists with establishing an SSH session to an EMR cluster master.

printUsage() {
	echo "Usage: $0 <cluster-id> <private-key-file> [<ssh arg>*]"
	echo "Please provide first the cluster-id printed by the 'launch-flux-capacitor' command."
	echo "Please provide second the local file containing the private key for the SSH key pair used by the EC2 nodes in the cluster."
	echo "Any additional options will be passed through to the ssh command."
	echo ""
	echo "To use an AWS CLI profile other than 'default', set the environment variable AWS_PROFILE."
}

CLUSTER_ID=$1; shift;
PRIVATE_KEY_FILE=$1; shift;
SSH_ARGS=$*

if [ -z "${CLUSTER_ID}" ]; then
	printUsage
	echo "If you do not know which key pair was used, running $0 <cluster-id> will print the key pair name."
	exit 1
fi

CLUSTER_DESCRIPTION=`aws --profile ${AWS_PROFILE:-"default"} emr describe-cluster --cluster-id ${CLUSTER_ID}`
EXIT_CODE=$?
if [ ${EXIT_CODE} -ne 0 ]; then
	echo "${CLUSTER_DESCRIPTION}"
	exit ${EXIT_CODE}
else
	PUBLIC_ADDR=`echo "${CLUSTER_DESCRIPTION}" | grep MasterPublicDnsName | cut -d '"' -f 4`
fi

if [ -z "${PRIVATE_KEY_FILE}" ]; then
	KEY_PAIR_NAME=`echo "${CLUSTER_DESCRIPTION}" | grep Ec2KeyName | cut -d '"' -f 4`
	printUsage
	echo "The name of the key pair used for cluster ${CLUSTER_ID} is: ${KEY_PAIR_NAME}"
	exit 1
fi

if [ ! -f "${PRIVATE_KEY_FILE}" ]; then
	echo "Not a readable file: '${PRIVATE_KEY_FILE}'"
	exit 2
fi

ssh -i "${PRIVATE_KEY_FILE}" ${SSH_ARGS} hadoop@${PUBLIC_ADDR}
