#!/bin/bash +O sourcepath

# Copyright (C) 2015 Commerce Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


LAUNCHER_HOME=${PWD}
CONFIGFILE=$1
if [ -z "${CONFIGFILE}" ]; then
    echo "Usage: $0 <configFile>"
    exit 1
fi
. ${CONFIGFILE}

aws --profile ${AWS_PROFILE} s3 mb ${RESOURCES_S3_URL}
aws --profile ${AWS_PROFILE} s3 sync ${LAUNCHER_HOME}/resources/s3/ ${RESOURCES_S3_URL}
