#!/bin/bash +O sourcepath

FLUXCAP_HOME=${PWD}
CONFIGFILE=$1
if [ -z "${CONFIGFILE}" ]; then
    echo "Usage: $0 <configFile>"
    exit 1
fi
. ${CONFIGFILE}

aws --profile ${AWS_PROFILE} s3 mb ${FLUXCAP_S3_URL}
aws --profile ${AWS_PROFILE} s3 sync ${FLUXCAP_HOME}/resources/s3/ ${FLUXCAP_S3_URL}
