#!/bin/sh

# Copyright (C) 2015 Commerce Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Waits for a cluster to be ready for use.

printUsage() {
	echo "Waits for a cluster to be ready to use."
	echo ""
	echo "Usage: $0 <cluster-id>"
	echo ""
	echo "Please provide the cluster-id printed by the 'launch-cluster' command."
	echo ""
	echo "To use an AWS CLI profile other than 'default', set the environment variable AWS_PROFILE."
}

CLUSTER_ID=$1
if [ -z "${CLUSTER_ID}" ]; then
	printUsage
	exit 1
fi

echo "Waiting... This can take 10 minutes or more if the cluster was launched recently."
time aws --profile ${AWS_PROFILE:-"default"} emr wait cluster-running --cluster-id ${CLUSTER_ID}
