#!/bin/sh

# Copyright (C) 2015 Commerce Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This only connects to Hive; you must also configure Hive tables for streams.
# (http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/query-kinesis-generate-data.html)

IS_MASTER=true
if [ -f /mnt/var/lib/info/instance.json ]; then
  IS_MASTER=`cat /mnt/var/lib/info/instance.json | tr -d '\n ' | sed -n 's|.*\"isMaster\":\([^,]*\).*|\1|p'`
fi
[ "$IS_MASTER" = "false" ] && exit 0


HIVE_METASTORE_ADDR=${HOSTNAME}

cat << EOF > drill-storage-streams.conf
{
  "name": "streams",
  "config": {
      "type": "hive",
      "configProps": {
         "hive.metastore.uris": "thrift://${HIVE_METASTORE_ADDR}:9083",
         "hive.metastore.sasl.enabled": "false"
      }
    }
  }
}
EOF

curl -s -S --retry 7 -X POST -H "Content-Type: application/json" \
 -d @drill-storage-streams.conf --url http://localhost:8047/storage/streams.json

rm -f drill-storage-streams.conf
