#!/bin/sh

# Copyright (C) 2015 Commerce Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#Note: Drill likes to have one or more folders beneath each workspace
#location to use as table names.

IS_MASTER=true
if [ -f /mnt/var/lib/info/instance.json ]; then
  IS_MASTER=`cat /mnt/var/lib/info/instance.json | tr -d '\n ' | sed -n 's|.*\"isMaster\":\([^,]*\).*|\1|p'`
fi
[ "$IS_MASTER" = "false" ] && exit 0


ARCHIVES_DFS_URL="$1"
ARCHIVES_PATH="$2"

if [ -z "${ARCHIVES_DFS_URL}" ]; then
  echo "Usage: $0 <ARCHIVES_DFS_URL> [ARCHIVES_PATH]"
  exit 1
fi

cat << EOF > drill-storage-stream_archives.conf
{
  "name": "stream_archives",
  "config": {
      "type": "file",
      "enabled": true,
      "connection": "${ARCHIVES_DFS_URL}",
      "workspaces": {
        "default": {
          "location": "${ARCHIVES_PATH:-/}",
          "writable": false,
          "defaultInputFormat": "json"
        }
      },
      "formats": null
    }
  }
}
EOF

curl -s -S --retry 7 -X POST -H "Content-Type: application/json" \
 -d @drill-storage-stream_archives.conf --url http://localhost:8047/storage/stream_archives.json

rm -f drill-storage-stream_archives.conf
