#!/bin/sh

# Copyright (C) 2015 Commerce Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

for f in /home/hadoop/hive/lib/emr-*.jar; do
  cp -af $f /home/hadoop/drill/jars/3rdparty/
done

for f in /usr/share/aws/emr/lib/emr-core-*.jar; do
  cp -af $f /home/hadoop/drill/jars/3rdparty/
done

for f in /home/hadoop/share/hadoop/common/lib/emr-*.jar; do
  cp -af $f /home/hadoop/drill/jars/3rdparty/
done

#TODO be more selective with aws-java-sdk;
#maybe leverage https://github.com/awslabs/emr-bootstrap-actions/blob/master/gradle/install-gradle-bootstrap.sh
for pattern in aws-java-sdk gson; do
  for f in /home/hadoop/share/hadoop/common/lib/${pattern}-*.jar; do
    cp -af $f /home/hadoop/drill/jars/3rdparty/
  done
done


JETS3T_VERSION=0.9.3
JETS3T_PKGNAME=jets3t-${JETS3T_VERSION}
JETS3T_URL=http://bitbucket.org/jmurty/jets3t/downloads/${JETS3T_PKGNAME}.zip
pushd /tmp
rm -rf ${JETS3T_PKGNAME}.zip ${JETS3T_PKGNAME}
echo Downloading Jets3t from ${JETS3T_URL}
wget ${JETS3T_URL}
unzip ${JETS3T_PKGNAME}.zip
cp -fv ${JETS3T_PKGNAME}/jars/${JETS3T_PKGNAME}.jar /home/hadoop/drill/jars/3rdparty
pushd /home/hadoop/drill/bin
cp -af hadoop-excludes.txt hadoop-excludes.txt.old
grep -v jets3t < hadoop-excludes.txt.old > hadoop-excludes.txt
popd
popd


# The service-nanny will restart it pretty quickly if we stop it. Experienced
# concurrent starts when invoking restart here, which led to port bind conflict,
# which led to infinite loop of failed starts.
sudo service drillbit stop
