#!/bin/sh

# Copyright (C) 2015 Commerce Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

VERSION=0.9.3

PKGNAME=jets3t-${VERSION}

URL=http://bitbucket.org/jmurty/jets3t/downloads/${PKGNAME}.zip

pushd /tmp
rm -rf ${PKGNAME}.zip ${PKGNAME}
echo Downloading Jets3t from ${URL}
wget ${URL}
unzip ${PKGNAME}.zip
cp -fv ${PKGNAME}/jars/${PKGNAME}.jar /home/hadoop/drill/jars/3rdparty
pushd /home/hadoop/drill/bin
cp -af hadoop-excludes.txt hadoop-excludes.txt.old
grep -v jets3t < hadoop-excludes.txt.old > hadoop-excludes.txt
popd
popd
sudo service drillbit restart
