#!/bin/sh

# Copyright (C) 2015 Commerce Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#TODO turn this into a service-nanny defn
#https://tnachen.wordpress.com/2013/12/24/drill-on-aws-emr/
nohup /home/hadoop/hive/bin/hive --service metastore > /mnt/var/log/hadoop/hive-metastore.out 2> /mnt/var/log/hadoop/hive-metastore.log &
